name: heatwaves
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - bokeh=2.4.3
  - pandas=1.4.3
  - matplotlib
  - geopandas==0.12.2
  - h3-py==3.7.4
  - scikit-mobility==1.3.1
  - dask=2022.11.0
  - numpy
  - pip
  - pip:
      - -e .
      - requests==2.28.1
